# Generated by Django 2.1.7 on 2019-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('picture', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
                ('star', models.CharField(max_length=5)),
            ],
        ),
    ]
