# Generated by Django 2.1.7 on 2019-07-17 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_restaurantinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
