# Generated by Django 2.1.7 on 2019-07-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_restaurantinfo_review_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('scontent', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=32)),
                ('start', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=32)),
                ('is_sub', models.CharField(max_length=32)),
                ('subid', models.CharField(max_length=32)),
            ],
        ),
    ]
