# Generated by Django 2.1.7 on 2019-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='res_id',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
