# Generated by Django 2.1.7 on 2019-07-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_review_res_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='subid',
            field=models.IntegerField(max_length=16),
        ),
    ]
