# Generated by Django 2.1.7 on 2019-07-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190719_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='subid',
            field=models.IntegerField(),
        ),
    ]
